from pwn import *
from time import sleep

p = process('start_dunnet')

# needs to be exact number of lines displayed
def dis(num_lines):
    for _ in range(num_lines):
        print(p.readline().decode('utf-8'), end='')
    print()
    sleep(.2)

def write_slow(command):
    for char in command:
        print(char, end='')
        sleep(.05)
    print()

def do(command):
    write_slow(command)
    p.sendline(command)

def check_egg(num_lines):
    out = []
    for _ in range(num_lines):
        out.append(p.readline().decode('utf-8'))

    
# could loop over each but dis is custom for each command
if __name__ == "__main__":
    dis(7)
    do('take all')
    dis(1)
    do('e')
    dis(4)
    do('e')
    dis(3)
    do('dig')
    dis(1)
    do('take all')
    dis(1)
    do('se')
    dis(3)
    do('take all')
    dis(1)
    do('se')
    dis(4)
    do('feed bear')
    dis(2)
    do('take all')
    dis(1)
    do('sw')
    dis(2)
    do('take all')
    dis(1)
    do('ne')
    dis(1)
    do('nw')
    dis(1)
    do('nw')
    dis(1)
    do('ne')
    dis(2)
    do('ne')
    dis(3)
    do('ne')
    dis(3)
    do('w')
    dis(7)
    do('put cpu in vax')
    dis(2)
    do('type')
    dis(4)
    do('toukmond')
    do('robert')
    dis(10)
    do('ftp gamma')
    dis(1)
    do('anonymous')
    dis(1)
    do('toukmond')
    dis(1)
    do('binary')
    dis(1)
    do('send lamp.o')
    dis(2)
    do('send shovel.o')
    dis(2)
    do('send key.o')
    dis(2)
    do('send bracelet.o')
    dis(2)
    do('quit')
    do('rlogin gamma')
    do('worms')
    dis(11)
    do('take all')
    dis(4)
    do('e')
    dis(3)
    do('n')
    dis(3)
    do('e')
    dis(6)
    do('drop shovel')
    dis(1)
    do('drop key')
    dis(1)
    do('drop bracelet')
    dis(1)
    do('take weight')
    dis(1)
    do('d')
    dis(3)
    do('drop weight')
    dis(2)
    do('nw')
    dis(2)
    do('u')
    dis(4)
    do('take all')
    dis(2)
    do('se')
    dis(2)
    do('d')
    dis(2)
    do('nw')
    dis(2)
    do('ne')
    dis(5)
    do('drop disk')
    dis(1)
    do('w')
    dis(1)
    do('s')
    dis(1)
    do('e')
    dis(4)
    do('turn dial clockwise')
    dis(1)
    do('turn dial clockwise')
    dis(1)
    do('turn dial clockwise')
    dis(3)
    do('turn dial counterclockwise')
    dis(1)
    do('w')
    dis(1)
    do('n')
    dis(1)
    do('e')
    dis(6)
    do('take all')
    dis(5)
    do('d')
    dis(2)
    do('nw')
    dis(1)
    do('u')
    dis(1)
    do('se')
    dis(1)
    do('d')
    dis(1)
    do('nw')
    dis(1)
    do('nw')
    dis(4)
    do('s')
    dis(3)
    do('s')
    dis(3)
    do('s')
    dis(2)
    do('s')
    dis(4)
    do('put bracelet in chute')
    dis(2)
    do('put diamond in chute')
    dis(2)
    do('s')
    dis(8)
    do('take all')
    dis(1)
    do('e')
    dis(3)
    do('e')
    dis(3)
    do('n')
    dis(3)
    do('d')
    dis(5)
    do('d')
    dis(3)
    do('sw')
    dis(2)
    do('e')
    dis(3)
    do('u')
    dis(3)
    do('dig')
    dis(1)
    do('take all')
    dis(1)
    do('d')
    dis(1)
    do('w')
    dis(1)
    do('w')
    dis(3)
    do('d')
    dis(3)
    do('e')
    dis(4)
    do('take all')
    dis(1)
    do('d')
    dis(2)
    do('s')
    dis(2)
    do('s')
    dis(3)
    do('s')
    dis(5)
    do('put disk in pc')
    dis(1)
    do('reset')
    dis(1)
    do('1')
    do('type foo.txt')
    dis(1)
    code = p.readline().decode('utf-8').split('is ')[1]
    print('The combination is', code, end='')
    code = code[:3] # get rid of the period
    do('exit')
    dis(3)
    do('n')
    dis(1)
    do('n')
    dis(1)
    do('n')
    dis(1)
    do('n')
    dis(2)
    do('n')
    dis(3)
    do('u')
    dis(3)
    do('put key in box')
    dis(2)
    do('u')
    dis(2)
    do('u')
    dis(3)
    do('ne')
    dis(2)
    do('ne')
    dis(4)
    do('take all')
    dis(1)
    do('d')
    dis(1)
    do('s')
    dis(3)
    do('d')
    dis(4)
    do('put gold in urinal')
    dis(1)
    do('put platinum in urinal')
    dis(1)
    do('flush')
    dis(2)
    do('n')
    dis(1)
    do('u')
    dis(1)
    do('w')
    dis(1)
    do(code)
    dis(5)
    do('cut cable')
    dis(4)
    do('exit')
    dis(6)
    do('take all')
    dis(1)
    do('e')
    dis(1)
    do('n')
    dis(6)
    do('take all')
    dis(3)
    do('w')
    dis(4)
    do('n')
    check_egg(7)
    do('n')
    check_egg(2)
    do('n')
    check_egg(2)
    do('n')
    check_egg(2)
    do('e')
    check_egg(2)
    do('s')
    check_egg(2)
    do('s')
    check_egg(2)
    do('s')
    check_egg(2)
    do('e')
    check_egg(2)
    do('n')
    check_egg(2)
    do('n')
    check_egg(2)
    do('n')
    check_egg(2)
    do('e')
    check_egg(2)
    do('s')
    check_egg(2)
    do('s')
    check_egg(2)
    do('s')
    check_egg(2)
    do('e')
    check_egg(2)
    do('e')
    check_egg(2)
    do('n')
    check_egg(4) # coins here
    do('w')
    check_egg(2) # but if the egg is there, then it's 3 lines
    do('n')
    # <check egg>
    do('e')
    # <check egg>
    do('n')
    # <check egg>
    do('w')
    # <check egg>
    do('e')
    do('enter')
    do('w')
    do('w')
    do('w')
    do('w')
    do('w')
    do('s')
    do('s')
    do('s')
    do('nw')
    do('exit')
    do('n')
    do('e')
    do('n')
    do('e')
    do('take all')
    do('s')
    do('take all')
    do('w')
    do('w')
    do('s')
    do('se')
    do('e')
    do('e')
    do('e')
    do('e')
    do('n')
    do('n')
    do('put glycerine in jar')
    do('put acid in jar')
    do('drop jar')
    do('enter')
    do('n')
    do('n')
    do('d')
    do('take all')
    do('u')
    do('put amethyst in garbage')
    do('put ruby in garbage')
    do('put silver in garbage')
    do('put egg in garbage')
    do('put coins in garbage')
    do('u')
    do('w')
    do('w')
    do('s')
    do('w')
    do('s')
    do('se')
    do('s')
    do('e')
    do('s')
    do('w')
    do('drop key')
    do('drop license')
    do('type')
    do('rlogin endgame')
    do('take all')
    do('n')
    do('n')
    do('answer <answer>')
    do('n')
    do('answer <answer>')
    do('n')
    do('answer <answer>')
    do('drop bracelet')
    do('drop diamond')
    do('drop gold')
    do('drop platinum')
    do('drop egg')
    do('drop coins')
    do('drop silver')
    do('drop ruby')
    do('n')
    do('take all')
    do('s')
    do('drop mona')
    do('s')
    do('answer <answer>')
    do('s')
    do('answer <answer>')
    do('s')
    do('answer <answer>')
    do('s')
    do('take all')
    do('n')
    do('n')
    do('answer <answer>')
    do('n')
    do('answer <answer>')
    do('n')
    do('answer <answer>')
    do('drop amethyst')
    do('quit')